### ISSUE TITLE
[Feature Request] Set Loglevel across multiple files

### ISSUE THREAD

**Issue by rsnk96** [metachris/logzero#108]
* logzero version:
* Python version: 3.6
* Operating System: Windows and Linux

### Description

I am trying to use logzero for a medium-scale project. However, I find it unnecessary that I have to manually change the loglevel for all the files when switching from debugging to runtime and vice-versa. It would be convenient if we could set the default loglevel in the main file (for instance) and all the other files would use the value set by the main file.

**Comment by vitasiku** [comment]
Exactly this. I checked out this module hoping that's the abstraction it offers over the logging module.

**Comment by dtamez** [comment]
logzero.setup_default_logger() works.  Set your level according to your configuration in one place and then in other files you can just use "from logzero import logger" and use the logger instance.
