### ISSUE TITLE
ncurses static line  feature

### ISSUE THREAD

**Issue by jarogames** [metachris/logzero#13]
I am just curious, if that would be possible :
Log into a static line (1st or last line on screen), while other `print()` commands would normally scroll the text...
It would be a kind of a status line, like in  screenrc...   Possible? Interested?
https://stackoverflow.com/questions/17122268/python-how-to-create-static-text-in-curses

**Comment by metachris** [comment]
Hi,

Thanks for the idea but logzero uses the standard Python logging facilities and this is not easily possible with it. Sounds more like an extra package to me, probably something like this already exists, too.

Cheers,
Chris
