### ISSUE TITLE
Rotating params for `setup_logger`

### ISSUE THREAD

**Issue by imbolc** [metachris/logzero#15]
It would be great to have there `maxBytes` and `backupCount` params, maybe with `file` prefix. Also looks like log prefix in `logfile` param is redundant.

**Comment by metachris** [comment]
Thank you for the feedback! That were my thoughts exactly, and I've just released v1.2.0 which does exactly that:

You can configure a rotating logfile for the default logger with [`logzero.logfile(..)`](https://logzero.readthedocs.io/en/latest/#i-logzero-logfile):

    logzero.logfile("/tmp/rotating-logfile.log", maxBytes=1000000, backupCount=3)

Or for a specific logger with [`setup_logger(..)`](https://logzero.readthedocs.io/en/latest/#i-logzero-setup-logger):

    logger = logzero.setup_logger(logfile="/tmp/rotating-logfile2.log", maxBytes=10, backupCount=3)

What do you think?

**Comment by imbolc** [comment]
Looks working, thank you :)
