### ISSUE TITLE
Different levels for console and file

### ISSUE THREAD

**Issue by imbolc** [metachris/logzero#16]
Is there a way to do this? I think it's a very common case - to send all the levels to the console, but only errors to file.

**Comment by metachris** [comment]
Good idea! Might be just a loglevel parameter to logzero.logfile(..)...
I'll take a look!

**Comment by metachris** [comment]
I Please take a look at this implementation: c5cb7fb8bbd61239590d32e4eb68927027316f8a

The only downside I see with the current implementation is that if you call `logzero.loglevel(..)`, it will override the custom loglevel of the filehandler. Perhaps this should not happen. What do you think?

**Comment by imbolc** [comment]
Yes, I think such behavior isn't obvious. I wouldn't use default logger at all :)

**Comment by metachris** [comment]
Fixed with afb82c2472841906a3038cf04f6a9264b18dc7f3 // v1.2.1 which was just released. You can now set specific loglevels for file handlers with both `logzero.logfile(..)` and `logzero.setup_logger(..)`.
