### ISSUE TITLE
Color support for Windows

### ISSUE THREAD

**Issue by thebigmunch** [metachris/logzero#18]
I assume you're aware due to the try/except on the import, Windows versions of Python do not ship with the curses module. While there are ways to get a Windows-compatible curses module, it's not a reasonable proposition when there are tried-and-trued alternatives to colored output for Python.

Most apps and packages use [colorama](https://github.com/tartley/colorama) for colored output, including some [colored](https://pypi.python.org/pypi/coloredlogs) [logging](https://pypi.python.org/pypi/logging-color-formatter) [packages](https://pypi.python.org/pypi/colorlog) that exist.

It's nice that logzero still works fine on Windows. But, colored output is certainly an attractive feature, so I hope you'll consider changing the method by which output is colorized to be cross-platform out-of-the-box.

Thanks for your time and effort.

**Comment by metachris** [comment]
Hello,

Thanks thats a good feedback, and I'm absolutely willing to accept improvements in this area. I don't have a Windows machine of VM at hand at the moment, so this probably won't be improved by myself soon. But as said, I'm willing to accept and mentor contributions in this regard.

Any thoughts on what's the best colored logging package in your opinion?

**Comment by thebigmunch** [comment]
Honestly, I had never looked any colored logging packages up before. I just figured it'd be best to link some examples and so searched PyPI for ``colored logging`` and linked the top recently created/updated packages.

Another tool I use daily, [httpie](https://github.com/jakubroztocil/httpie), uses colorama along with Pygments to tokenize and color its output akin to syntax highlighting. [better-exceptions](https://github.com/Qix-/better-exceptions) conditionally [installs](https://github.com/Qix-/better-exceptions/blob/master/setup.py#L17) and [uses](https://github.com/Qix-/better-exceptions/blob/master/better_exceptions/color.py#L53) colorama for its coloring.

Unfortunately, I can't justify spending time on this at present. I have too many projects that have long suffered neglect due to a lack of hobby time. I've only just found time for some of that work when I saw this package. I was hoping to drop it into a project but will have to move on without it until I catch up on my backlog of work : (

**Comment by metachris** [comment]
First of all, thanks for the research and the references!

I will take a look at color support for Windows / colorama integration soon, if nobody else contributes something for this.

I hope you'll try out logzero by dropping it into projects anyway, I think that you'll be happy with it and I'm hoping that you continue to submit feedback and ideas!

Thanks ;)

**Comment by metachris** [comment]
So, I've installed Windows in a VM and played around with colorama, and it seems to work quite nicely: https://github.com/metachris/logzero/commit/4207194dc3f752b6c6536bba94f31a04a0de23be#diff-27e20f4aad63c2b9a1ce2974b00a4da4

What do you think?

**Comment by metachris** [comment]
So, I've installed Windows in a VM and played around with colorama, and it seems to work quite nicely. I'm considering to release this in pretty much this form: #20

Any thoughts?

**Comment by thebigmunch** [comment]
Looks fine to me. Thanks. Seems like I'll get to put this into [gmusicapi-scripts](https://github.com/thebigmunch/gmusicapi-scripts) for the 1.0.0 release after all : P

**Comment by metachris** [comment]
I've just merged this into master and released v1.3.0

@thebigmunch can you please confirm that it works for you on Windows?

**Comment by thebigmunch** [comment]
I had already tested your PR, bit I can give it a post-release test when I get home in a few hours.

**Comment by thebigmunch** [comment]
Still works well : P

**Comment by metachris** [comment]
Thanks! Awesome.
