### ISSUE TITLE
logzero is listed in the openSUSE packages but can't seem to install them

### ISSUE THREAD

**Issue by metachris** [metachris/logzero#22]
As noted in #21, logzero is listed in the openSUSE packages:

* https://software.opensuse.org/package/python2-logzero
* https://software.opensuse.org/package/python3-logzero

I tried in Docker with openSUSE 42.2, but can't seem to install the packages:

    # zypper install python2-logzero
    Loading repository data...
    Reading installed packages...
    'python2-logzero' not found in package names. Trying capabilities.
    No provider of 'python2-logzero' found.

@sebix any idea?

**Comment by sebix** [comment]
New packages are not added to already released versions (42.2 is from last year). If you want to do that, follow the linked instructions (adding the devel:languages:python repository to "backport" it). For 42.3 is also too late. AFAIK other distros are doing it this way too.

For the rolling release distro Tumblweed, that's possible soon.

**Comment by sebix** [comment]
And instead of listing all releases and the status of a package, and keeping this information up to date, my idea was to just link this information. The link does not require any periodic update of itself.

**Comment by sebix** [comment]
The linked webpage lists a "official release" for openSUSE Tumbleweed (the rolling release distro). You can install logzero in Tumbleweed with `sudo zypper in python-logzero`.

**Comment by metachris** [comment]
Thanks!
