### ISSUE TITLE
Usage with multiprocessing and single rotated logfile

### ISSUE THREAD

**Issue by pylipp** [metachris/logzero#222]
* logzero version: 1.5.0
* Python version: 3.6.5
* Operating System: Ubuntu 16.04

### Description

I'm trying to use logzero in a multiprocessing context using a single rotated logfile.
I obtain errors from the Python logging module that moving files fails.

### What I Did

I created a MWE [here](https://github.com/pylipp/logzero-mp) including all instructions to set up and run it.

If my approach is valid, I see a clash with logzero's claim to feature 'Multiple loggers can write to the same logfile (also across multiple Python files)'.
I'm not entirely sure whether this is not actually a limitation of Python's internal logging module, please point out if so :)

**Comment by sinnud** [comment]
What I met is, when multiprocessing have log to standard output (screen), the main log file didn't include log output from sub-thread.
My solution is, create separate log file for each thread and let each thread has own log file. After all thread finish, collect all thread log files into main log file and delete these temporary thread log files.

**Comment by pylipp** [comment]
@sinnud That's a proper work-around.
My opinion still stands that I'd expect a logging package to provide such functionality. And if the package does not provide it, I'd like this to be explicitly stated somewhere.

**Comment by metachris** [comment]
Looking into it...

**Comment by metachris** [comment]
This example seems to work, as in both log outputs show up in the logfile:

```python
import multiprocessing
import time
import logzero


class LazyLogProcess(multiprocessing.Process):
    """A process that logs at a specific rate."""
    def set_text(self, text):
        self.text = text

    def run(self):
        logger = logzero.setup_logger("lazy", logfile='/tmp/y1')

        for _ in range(1000):
            logger.warn(self.text)
            time.sleep(0.1)


def main():
    lazy_log_process1 = LazyLogProcess()
    lazy_log_process1.set_text('111111111111')
    lazy_log_process1.start()

    lazy_log_process2 = LazyLogProcess()
    lazy_log_process2.set_text('22222222222')
    lazy_log_process2.start()


if __name__ == "__main__":
    main()
```

**Comment by metachris** [comment]
Closing this issue for now, unless we have code that reproduces the problem.
