### ISSUE TITLE
Is there a way to use use "logging.setLoggerClass"

### ISSUE THREAD

**Issue by aaronlelevier** [metachris/logzero#275]
* logzero version: logzero==1.5.0
* Python version: Python 3.7.1
* Operating System: Mac OS 10.14

### Description

Is there a way to use `setLoggerClass` like in this SO Answer? https://stackoverflow.com/a/37025517/1913888

### What I Did

When logging errors, I'd like to accumulate them in a global ERRORS list.

From reading the code, I'm not sure how to set the logger class. I didn't see `logging.Logger` being subclassed.

Your help is much appreciated. 

Great Library BTW

Thanks

**Comment by metachris** [comment]
Yes, you can use `logging. setLoggerClass`. You just need to call `logzero.reset_default_logger()` afterwards to apply it to the default logger (or setup your logger afterwards however you want it).
