### ISSUE TITLE
setup_logger() with level set cannot be changed

### ISSUE THREAD

**Issue by mosesontheweb** [metachris/logzero#280]
* logzero version: 1.5.0
* Python version: 3.7.7
* Operating System: MacOS 10.14.6

### Description

I'm using a logging instance of loguru and recognized that this instance does not display messages of a lower value than originally set with level, even though `.setLevel` has set the new the level. See example below.

### What I Did

```
>>> from logzero import setup_logger
>>> import logging
>>> logfix = setup_logger(level=logging.INFO)
>>> logfix.debug("I'm a debug message")  # expected
>>> logfix.info("I'm an info message")  # expected
[I 200312 21:04:09 <stdin>:1] I'm an info message
>>> logfix.setLevel(logging.DEBUG)
>>> logfix.level
10
>>> logfix.debug("I'm a debug message!")  # NOT expected
>>> logfix.info("I'm an info message!")
[I 200312 21:04:54 <stdin>:1] I'm an info mesasge!
>>> logfix2 = setup_logger()
>>> logfix2.setLevel(logging.INFO)
>>> logfix2.debug("Debug")
>>> logfix2.info("Info")
[I 200312 21:05:38 <stdin>:1] Info
>>> logfix2.setLevel(logging.DEBUG)
>>> logfix2.debug("Debug")
[D 200312 21:05:51 <stdin>:1] Debug
>>> logfix2.info("Info")
[I 200312 21:05:54 <stdin>:1] Info
>>> logfix2.level
10
```

**Comment by metachris** [comment]
You should use the correct loglevel when calling `setup_logger`, or use `logzero.loglevel(...)`, rather than `logger.setLevel` (which does not necessarily apply the level to all handlers).
