### ISSUE TITLE
Raising and Logging exception

### ISSUE THREAD

**Issue by xvrdm** [metachris/logzero#35]
* logzero version: 1.3.0
* Python version: 3.6
* Operating System: Ubuntu

### Description

I am using logzero and pytest. When an exception occur, I would like to be able to catch it in the log, but also to test that it was raised in my unittest. Currently, the only way I managed to do this is to catch the exception, log it and raise it again. That doesn't feel like the right way (maybe it is).

Do you have a leaner way to recommend?

### What I Did

```python
# in main.py
    if publisher:
        try:
            timezone = config.TIMEZONES[publisher]
        except KeyError as e:
            logger.exception({
                "error": e,
                "message": f"Missing timezone ID for publisher: {publisher}"
            })
            raise KeyError
```

Thanks for the great package, a lot simpler than anything else I have experienced for logging. #

**Comment by thebigmunch** [comment]
This is exactly the recommended pattern in Python except that you should just use a bare ``raise`` instead of ``raise KeyError``. That way, the original exception is raised instead of a new KeyError instance.

**Comment by metachris** [comment]
Yes, as @thebigmunch says, this is the standard pattern of logging exceptions. Perhaps it would be possible to add a helper a la `with logzero.try():`, but this is out of scope at the moment. Although I'm open to further discussion about this topic!

**Comment by xvrdm** [comment]
Thanks both! If that's the recommended pattern, happy to stick with it :)
