### ISSUE TITLE
Logfile JSON encode

### ISSUE THREAD

**Issue by ScrimForever** [metachris/logzero#355]
* logzero version: 1.6.2
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

logger.json(True) 
I cant encode in UTF-8 , my special characters, like Ç , ç , ã , é and others, on file appear \x0231 etc .

[logfile.log](https://github.com/metachris/logzero/files/5531449/logfile.log)

**Comment by metachris** [comment]
Should be fixed in PR #357. Using UTF-8 by default now

**Comment by metachris** [comment]
Fixed and released in logzero v.1.6.3
