### ISSUE TITLE
setup_default_logger of para maxBytes, backupCount not used

### ISSUE THREAD

**Issue by qtdwzAdam** [metachris/logzero#384]
* logzero version: 1.6.3
* Python version: 2.7
* Operating System: Windows 10 (20H2 19042.630)

### Description
setup_default_logger of para maxBytes, backupCount not used

https://github.com/metachris/logzero/blob/master/logzero/__init__.py#L307

![image](https://user-images.githubusercontent.com/3243008/110586351-11081600-81ad-11eb-9fe2-a265024870a2.png)

**Comment by metachris** [comment]
Thanks! Github somehow didn't send me a mail on this. Fixing it now

**Comment by metachris** [comment]
Fixed in v1.7.0
