### ISSUE TITLE
in logfile() fuction, filename arg type error?

### ISSUE THREAD

**Issue by joeyac** [metachris/logzero#41]
* logzero version:1.3.0
* Python version:3.5.2
* Operating System:ubuntu 16.04

### Description

in logfile() fuction, filename arg type error?Should it be string?

> :arg int filename: Filename of the logfile. Set to `None` to disable logging to the logfile.

### What I Did

change the type of filename to string.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by metachris** [comment]
I'm not sure I can follow. Yes, `filename` should be a string or `None`. What did you use, and what kind of error did you receive?

**Comment by thebigmunch** [comment]
They mean that the type is given incorrectly in the [docstring](https://github.com/metachris/logzero/blob/master/logzero/__init__.py#L395).

**Comment by metachris** [comment]
Thanks. Fixed in the build that's just upcoming.
