### ISSUE TITLE
Setting a loglevel for logfiles

### ISSUE THREAD

**Issue by LuckyJosh** [metachris/logzero#57]
Hi,

I would like to set the logging level for a logfile to `DEBUG` but leave the logging level
for the console log at `INFO`, to log debug information to the logfile without cluttering the console.
For example by defining a custom logger via

`logzero.setup_logger(logfile="custom_logfile.log", level=logging.INFO, fileLoglevel=logging.DEBUG)`.

This does not work as I expected. After some testing I came to the conclusion that
the loglevel set via `fileLoglevel` can not be lower (only higher) than the loglevel set via `level`.
If a lower level is set via `fileLoglevel` it gets overwritten by `level`.
 
Is there a specific reason for this behavior?

**Comment by metachris** [comment]
I would discourage you from using `setup_logger`. The default logger is already setup, and you can configure it more easily and more versatile:

* Use `logzero.loglevel(level=logging.DEBUG, update_custom_handlers=False)` to setup the general loglevel
* Use `logzero.logfile(filename, formatter=None, mode='a', maxBytes=0, backupCount=0, encoding=None, loglevel=None)` to setup the logfile with a specific `loglevel` for the file only. This will not get overwritten by `logzero.loglevel(..)`

**Comment by metachris** [comment]
Thanks for the example. Yeah, I would also expect the DEBUG message in there. Will take a look tomorrow!

**Comment by LuckyJosh** [comment]
Thank you, I very much appreciate your support!

**Comment by LuckyJosh** [comment]
I have to admit that it did not occur to me until now that the cause of this "problem" might lie in the `logging` library itself. And it seems to be the case as can be seen in these to stackoverflow threads [here](https://stackoverflow.com/questions/11111064/how-to-set-different-levels-for-different-python-log-handlers) or [here](https://stackoverflow.com/questions/6652727/different-logging-levels-for-filehandler-and-display-in-python).
The issue seems to be that one handler is not enough for this purpose. You need to create a `StreamHandler` and a `FileHandler` with their respective logleves and the loglevel of the logger has to be the smallest one of those two.

**Comment by metachris** [comment]
Oh, okay. Thanks for the research and information. I'll take a look when I find the time.

**Comment by mgiaco** [comment]
It would also be great if the console could be disable if needed. I do not find any way without changing the code.

**Comment by alekna** [comment]
The workaround to this problem is to change log level of `StreamHandler` handler directly without touching `logzero.logger.level`.

Not a nice way, but works for me: 
```
logzero.logfile('test.log', loglevel=logging.DEBUG)
logzero.logger.handlers[0].level = logging.INFO
```

Logzero could easily abstract this bug away in a nice way.

**Comment by LuckyJosh** [comment]
@alekna
Yes, you are right, there are definitely workarounds for this. 

However it just seems to defy the purpose of this package to interact with the handlers directly, so I refrained from using one up to now.

But I think as far as workarounds go the one you suggested is quite nice, actually, might give it a try. :+1:

**Comment by TheButlah** [comment]
having a `logzero.logstream` to abstract interaction with the `StreamHandler` like `logzero.logfile` abstracts interaction with the `FileHandler` would be really nice. I'm having the same issue where I want the file to have a lower log level than the stream, and I can't do it without the hacky method mentioned by @alekna

**Comment by Burathar** [comment]
@metachris 
> I would discourage you from using `setup_logger`. The default logger is already setup, and you can configure it more easily and more versatile:
> 
>     * Use `logzero.loglevel(level=logging.DEBUG, update_custom_handlers=False)` to setup the general loglevel
> 
>     * Use `logzero.logfile(filename, formatter=None, mode='a', maxBytes=0, backupCount=0, encoding=None, loglevel=None)` to setup the logfile with a specific `loglevel` for the file only. This will not get overwritten by `logzero.loglevel(..)`
> 
> 
> Does that work for you like this?

I sort of had the same issue because I used the setup_logger function, which doesn't seem to work as expected. (The following snippet turned out to work for me)

```python3
log = logzero.setup_logger(logfile='log.log', level=50, fileLoglevel=10)
log.level = 10
```

I didn't find any warnings in the documentation that the function shouldn't be used(in this way), so it confused me until I found this reaction of yours. Would it be possible to either fix the behaviour, or mention somewhere that it shouldn't be used like this?

**Comment by metachris** [comment]
Thanks for the reports and discussion. I'm taking a fresh look at this now.
Anyone still around and motivated to take a look at a possible approach?

**Comment by metachris** [comment]
Please take a look at the fix/implementation in #339 - i think that will work.

**Comment by LuckyJosh** [comment]
First of all I have to admit that I am on some kind of a hiatus from programming in general, 
and I have not looked into this issue in particular for quite some time. 
But I still wanted to give my two cents:

I just ran my test file posted above (using the current version `1.5.0`) and the behaviour has not changed. 
The logfile `debug.log` still does not contain the message at `DEBUG`-level. 
Furthermore, looking at #339 I dont get the impression that the changes made there could have fixed this issue.

**Comment by metachris** [comment]
Thanks for the message. I'm sorry, I've accidentally referenced the wrong PR :) This is the correct one: https://github.com/metachris/logzero/pull/338

To test it you'd need to checkout that branch (`logfile-loglevel`).

Furthermore, wishing you all the best on your hiatus. What are you up to these days?

**Comment by LuckyJosh** [comment]
Sorry, for the late answer.
Thanks for your kind wishes. : ) 
Im currently in the transition phase from physics/data-analysis to physics/math-education.
