### ISSUE TITLE
how to use on module level?

### ISSUE THREAD

**Issue by mgiaco** [metachris/logzero#62]
Hi, 

Normally I use 

```
_logger = logging.getLogger(__name__)
```
on every python module so.

How can I switch to logzero? I am missing the __name__

thx

**Comment by LuckyJosh** [comment]
You would have to use `logzero.setup_logger` to define a custom logger, which does take an
optional `name` argument. From looking at the code the default `name` for a custom logger actually seems to be `__name__`.

**Comment by metachris** [comment]
Yeah, you can either use `setup_logger` if you want a custom name, or if one logger is enough you could just do `from logzero import logger`.

https://logzero.readthedocs.io
