### ISSUE TITLE
logging to file only

### ISSUE THREAD

**Issue by mgiaco** [metachris/logzero#63]
Hi,

Is there a way to log to file only.

So I taught the level is the log level for the console and fileLoglevel is the level for the file. If I set 
this here:
```
my_logger = setup_logger(logfile=path, maxBytes=1024 * 1024, backupCount=3, level=logging.ERROR,
                                         fileLoglevel=logging.INFO)
```
it dose not work. I use 
my_logger.info(...

but nothing is printed to the file. So there is something wrong with level and file level I think.

So I would like to use logzero as a file logger only parallel to the the normal python logger. Do you see any problem here?

cheers
mathias

**Comment by mgiaco** [comment]
Ah sorry this is the same error as  #57

**Comment by metachris** [comment]
Yeah, it's currently not possible to easily remove the console handler. You could still go through the handlers manually and remove it.
