### ISSUE TITLE
upload on conda-forge

### ISSUE THREAD

**Issue by carlodri** [metachris/logzero#67]
Hi @metachris, I was wondering if you were interested in uploading the package on [conda-forge](https://conda-forge.org/), which, as you probably know, is a widespread package managing system. If you agree, I can prepare the feedstock recipe.

**Comment by metachris** [comment]
Hi!

Thanks for the suggestion, this was not on my radar. Would be happy have logzero available on conda-forge! What would be the steps, and what kind of maintenance would be needed for new releases?

**Comment by carlodri** [comment]
the steps are summarized [here](https://conda-forge.org/#add_recipe), if you want I already did this and I can prepare the recipe putting you as well as a maintainer.

maintenance requires manual bumping of versions there, but there is a single place where the number has to be changed (together with the package SHA256). It's not a big deal.

**Comment by metachris** [comment]
Thanks, I would appreciate if you could prepare this 👍

**Comment by metachris** [comment]
@carlodri what are the extra steps when i release a new version of logzero on pypi?

**Comment by carlodri** [comment]
you have precise instructons [here](https://github.com/conda-forge/logzero-feedstock#updating-logzero-feedstock) and [here](https://conda-forge.org/#update_recipe).

In summary, you need to:
* fork the [feedstock repo](https://github.com/conda-forge/logzero-feedstock)
* update the package version tag in `recipe/meta.yaml` (_e.g._ `{% set version = "1.3.1" %}`)
* update the package source SHA256 in `recipe/meta.yaml` (_e.g._ `{% set sha256 = ...}`). You can easily copy & paste it from [here](https://pypi.org/project/logzero/#files)
* submit a PR, wait for tests to succeed and merge it

**Comment by metachris** [comment]
Great, thanks!

**Comment by metachris** [comment]
@carlodri I've published v1.6.2 just now: https://pypi.org/project/logzero/

Could you update the build on conda-forge?

**Comment by carlodri** [comment]
sure, looking into it now, there are some CI fails

**Comment by carlodri** [comment]
done! just give a couple of hours for the conda DBs to update

**Comment by metachris** [comment]
Awesome, thank you ❤️
