### ISSUE TITLE
Add mail handler to error/warn log entries

### ISSUE THREAD

**Issue by davidhuser** [metachris/logzero#71]
Used this logger for the first time, it's nice! A buffered mail sender (so we don't send a message each time an exception/warning is thrown) would be a nice feature to add, used this a while ago in another repository:
https://gist.github.com/asfaltboy/5998415

What do you think?

**Comment by metachris** [comment]
You could just add this as a custom handler like so: https://logzero.readthedocs.io/en/latest/#adding-custom-handlers-eg-sockethandler
