### ISSUE TITLE
[Feature suggestion] Add compression support for backup logs

### ISSUE THREAD

**Issue by luizfzs** [metachris/logzero#72]
It would be awesome if there was the option to compress the backup logs. Since text files have a great compression ratio, it would save a ton of space.

**Comment by metachris** [comment]
Good point. You could check the standard Python logging facilities if they have support for it, but I doubt it, actually. Alternatively you could setup a cronjob that does it, or just a logrotate config.

**Comment by metachris** [comment]
Feel free to reopen this issue if you have more infos about how to actually go about it.
