### ISSUE TITLE
Suggestion/Question - Rotating Logs

### ISSUE THREAD

**Issue by dseptem** [metachris/logzero#8]
Does this module support rotating log files?
For what I've seen, logzero doesn't provide functionality to rotate logs, which will result in enormous log files, with enough time.
My production environments usually keep 7 rotating log files, one for each day of the week, which prevents the log-explosion issue.

**Comment by metachris** [comment]
Thanks for the input! I'll add support for other [logging handlers](https://docs.python.org/2/library/logging.handlers.html) (eg. Rotating, Socket, etc) as soon as I find the time, and will update this issue!

**Comment by metachris** [comment]
I've just added some documentation about how to use custom handlers with an example for RotatingFileHandler: https://logzero.readthedocs.io/en/latest/#adding-custom-handlers-eg-rotatinglogfile

**Comment by dseptem** [comment]
Thanks a lot :)
