### ISSUE TITLE
Readme should explain relationship with logging module

### ISSUE THREAD

**Issue by Julian-O** [metachris/logzero#9]
* logzero version: N/A
* Python version: N/A
* Operating System: N/A

### Description

This is some friendly feedback on my first impression about reading about `logzero`. I thought it was a *competitor* to Python's excellent `logging` module, rather than an introduction/stepping-stone.

I had delve quite deep to find that it is a front-end to it, which means all the power of `logging` is available to the user as they become more familiar with it, and their project grows.

I suggest you make this clearer, earlier in the Readme/Docs. It might help prevent questions like #8, too, as people realise there is plenty of functionality waiting for them behind the curtain.

Good luck with the project.

**Comment by metachris** [comment]
Thanks for the feedback! I agree, this should be made clearer!

**Comment by metachris** [comment]
@Julian-O thank you so much for your feedback. I've added the information to both the README and the documentation.

Do you think it is clear enough now? Do you have any further suggestions

**Comment by Julian-O** [comment]
Looks great. Cheers.
