### ISSUE TITLE
Is time rotating logging supported in logzero?

### ISSUE THREAD

**Issue by epicGeek** [metachris/logzero#99]
* logzero version: 1.5.0
* Python version: 2.7.14
* Operating System: CentOS 7 / Windows 7

### Description

Is time rotating logging supported in logzero?
I read some source code and it seems there is no time rotating logging.
Will it be a new feature in later version? Thank you.

**Comment by metachris** [comment]
You could manually add a [`TimedRotatingFileHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler)

I'll think a little bit about whether to add it into logzero directly.
